repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        args:
          - --autofix
  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.5.4
    hooks:
      - id: pmd
      - id: cpd
      - id: checkstyle
