# datasource
spring:
  profiles:
    active: prod
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}


auto-table:
  enable: true
  model-package: top.suyiiyii.sims.entity