# datasource
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}


auto-table:
  enable: true
  model-package: top.suyiiyii.sims.entity

jwt:
  secret: ${JWT_SECRET}

S3:
  ENDPOINT: ${S3_ENDPOINT}
  BUCKET: ${S3_BUCKET}
  ACCESS_KEY: ${S3_ACCESS_KEY}
  SECRET_KEY: ${S3_SECRET_KEY}

springdoc:
  default-support-form-data: true