apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: sims
        resources: {}
        env:
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: secret
              key: spring.datasource.url
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: spring.datasource.username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: spring.datasource.password
        - name: DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: spring.datasource.driver-class-name
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret
              key: jwt.secret
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: secret
              key: S3.ENDPOINT
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: secret
              key: S3.BUCKET
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: S3.ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: S3.SECRET_KEY
              

status: {}
