apiVersion: v1
data:
  spring.datasource.url: {{ .Values.spring.datasource.url | b64enc | quote }}
  spring.datasource.username: {{ .Values.spring.datasource.username | b64enc | quote }}
  spring.datasource.password: {{ .Values.spring.datasource.password | b64enc | quote }}
  spring.datasource.driver-class-name: {{ .Values.spring.datasource.driver-class-name | b64enc | quote }}
  jwt.secret: {{ .Values.jwt.secret | b64enc | quote }}
  
kind: Secret
metadata:
  creationTimestamp: null
  name: secret
