apiVersion: v1
data:
  spring.datasource.url: {{ .Values.spring.datasource.url | b64enc | quote }}
  spring.datasource.username: {{ .Values.spring.datasource.username | b64enc | quote }}
  spring.datasource.password: {{ .Values.spring.datasource.password | b64enc | quote }}
  spring.datasource.driver-class-name: {{ .Values.spring.datasource.driverClassName | b64enc | quote }}
  jwt.secret: {{ .Values.jwt.secret | b64enc | quote }}
  S3.ENDPOINT: {{ .Values.S3.ENDPOINT | b64enc | quote }}
  S3.BUCKET: {{ .Values.S3.BUCKET | b64enc | quote }}
  S3.ACCESS_KEY: {{ .Values.S3.ACCESS_KEY | b64enc | quote }}
  S3.SECRET_KEY: {{ .Values.S3.SECRET_KEY | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: secret
